### ISSUE TITLE
Download of preprocessed vectors not working

### ISSUE THREAD

**Issue by thomas-imt** [andreapdr/gFun#1]
Hello!

I just wanted to try out the project and start with the preprocessed dataset vectors, but the linked http://hlt.isti.cnr.it/funnelling/ seems to be down.

Is there an alternative download?

Greetings!
Thomas

**Comment by andreapdr** [comment]
Hello Thomas, thank you for pointing that out! Indeed, we had some problems with the server hosting the datasets but now we are working on it! I'll get back to you as soon as we fix this!

**Comment by andreapdr** [comment]
Hello Thomas, we are still having some troubles with our original hosting machine. In the meantime, I have uploaded both pre-processed datasets on my Drive so that you can download them!
[https://drive.google.com/drive/folders/1kEZINbSh6RyaeEaz739E_CTKPK48MHGD?usp=sharing](https://drive.google.com/drive/folders/1kEZINbSh6RyaeEaz739E_CTKPK48MHGD?usp=sharing)

Regards,
Andrea

**Comment by thomas-imt** [comment]
Thank you, the download worked! (I'll try to run things tomorrow)
